version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=flaskapp
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - db
    restart: always

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flaskapp
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
